project:
  output-dir: _output
  type: book

book:
  title : "Report - DataBase Project - IFEBY140"
  chapters:
    - index.qmd
    - analysis.qmd
    - modelization.qmd
    - implementation.qmd
    - request_examples.qmd
  downloads: [pdf]

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    theme: cosmo
    title: "Report_DataBase_Project_IFEBY270"
    toc: true
    geometry:
      - top=22.4mm
      - left=25.4mm
      - right=25.4mm
      - bottom=25.4mm